# These are supported funding model platforms

patreon: luxdamore
open_collective: luca-iaconelli
ko_fi: luxdamore
liberapay: luxdamore
issuehunt: luxdamore
otechie: luxdamore
custom: ['https://www.paypal.me/luxdamore']
